import type { Category, Course, Testimonial } from "./types";

export const footerLinks = [
  {
    title: "Featured Courses",
    links: [
      { label: "Featured Courses", href: "#" },
      { label: "Featured Categories", href: "#" },
      { label: "Business", href: "#" },
      { label: "IT", href: "#" },
      { label: "Design", href: "#" },
    ],
  },
  {
    title: "Development",
    links: [
      { label: "Development", href: "#" },
      { label: "Marketing", href: "#" },
      { label: "Photography", href: "#" },
      { label: "Finance", href: "#" },
      { label: "Sport", href: "#" },
    ],
  },
  {
    title: "Become a Creator",
    links: [
      { label: "Become a Creator", href: "#" },
      { label: "Affiliate Program", href: "#" },
      { label: "Contact", href: "#" },
      { label: "Help", href: "#" },
      { label: "About", href: "#" },
    ],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "Sarah M.",
    role: "Enthusiastic Learner",
    avatar: "/images/home-image/sarah.png",
    quote:
      '"ByteSpace has transformed my approach to learning. The diverse range of courses and the quality of content provided by creators have exceeded my expectations. The platform truly fosters a sense of community and lifelong learning."',
  },
  {
    id: 2,
    name: "James L.",
    role: "Lifelong Learner",
    avatar: "/images/home-image/james.png",
    quote:
      '"I\'ve tried several online learning platforms, and ByteSpace stands out for its vibrant community and the variety of courses available. The easy navigation and engaging content make it a go-to platform for continuous skill development."',
  },
  {
    id: 3,
    name: "Alex B.",
    role: "Inspired Creator",
    avatar: "/images/home-image/Alex.png",
    quote:
      '"As a creator, ByteSpace has been a game-changer for me. The Course Editor is user-friendly, and the support from the community is incredible. It\'s fulfilling to see my courses making a positive impact on learners globally."',
  },
];

export const categories: Category[] = [
  { id: "featured", name: "Featured" },
  { id: "music", name: "Music" },
  { id: "drawing-painting", name: "Drawing & Painting" },
  { id: "marketing", name: "Marketing" },
  { id: "animation", name: "Animation" },
  { id: "social-media", name: "Social Media" },
  { id: "uiux-design", name: "UI/UX Design" },
  { id: "creative-marketing", name: "Creative Marketing" },
  { id: "digital-illustration", name: "Digital Illustration" },
  { id: "film-video", name: "Film & Video" },
  { id: "crafts", name: "Crafts" },
  { id: "freelance", name: "Freelance & Entrepreneurship" },
  { id: "graphic-design", name: "Graphic Design" },
  { id: "photography", name: "Photography" },
  { id: "productivity", name: "Productivity" },
  { id: "web-development", name: "Web Development" },
  { id: "data-science", name: "Data Science" },
  { id: "cooking", name: "Cooking" },
];

export const INITIAL_CHIPS = 16;

export const courses: Course[] = [
  {
    id: 1,
    title: "Learn Figma from Basic",
    instructor: "purepearl studio",
    rating: 4.5,
    reviewCount: 59,
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    price: 25,
    priceType: "lifetime",
    category: "uiux-design",
    thumbnail: "/images/course/course1.jpg",
    studentCount: 420,
    isFeatured: true,
  },
  {
    id: 2,
    title: "Build Digital Asset",
    instructor: "purepearl studio",
    rating: 4.5,
    reviewCount: 59,
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    price: 25,
    priceType: "lifetime",
    category: "graphic-design",
    thumbnail: "/images/course/course2.jpg",
    studentCount: 420,
    isFeatured: true,
  },
  {
    id: 3,
    title: "the Power of Big Data",
    instructor: "purepearl studio",
    rating: 4.5,
    reviewCount: 59,
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    price: 25,
    priceType: "lifetime",
    category: "data-science",
    thumbnail: "/images/course/course3.jpg",
    studentCount: 420,
    isFeatured: true,
  },
  {
    id: 4,
    title: "Balancing Productivity and Well-being",
    instructor: "purepearl studio",
    rating: 4.5,
    reviewCount: 59,
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    price: 25,
    priceType: "lifetime",
    category: "productivity",
    thumbnail: "/images/course/course4.jpg",
    studentCount: 420,
    isFeatured: true,
  },
  {
    id: 5,
    title: "Mastering Money Management",
    instructor: "purepearl studio",
    rating: 4.5,
    reviewCount: 59,
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    price: 25,
    priceType: "lifetime",
    category: "freelance",
    thumbnail: "/images/course/course5.jpg",
    studentCount: 420,
    isFeatured: true,
  },
  {
    id: 6,
    title: "From Idea to Startup Success",
    instructor: "purepearl studio",
    rating: 4.5,
    reviewCount: 59,
    level: "Beginner",
    lessons: 17,
    duration: "2 hours 16 mins",
    comments: 59,
    price: 25,
    priceType: "lifetime",
    category: "freelance",
    thumbnail: "/images/course/course6.jpg",
    studentCount: 420,
    isFeatured: true,
  },
  {
    id: 7,
    title: "Music Production Masterclass",
    instructor: "sound studio",
    rating: 4.8,
    reviewCount: 120,
    level: "Intermediate",
    lessons: 24,
    duration: "4 hours 30 mins",
    comments: 85,
    price: 35,
    priceType: "lifetime",
    category: "music",
    thumbnail: "/images/course/course1.jpg",
    studentCount: 650,
  },
  {
    id: 8,
    title: "Digital Painting Techniques",
    instructor: "art academy",
    rating: 4.7,
    reviewCount: 95,
    level: "Beginner",
    lessons: 20,
    duration: "3 hours 45 mins",
    comments: 72,
    price: 30,
    priceType: "lifetime",
    category: "drawing-painting",
    thumbnail: "/images/course/course2.jpg",
    studentCount: 380,
  },
  {
    id: 9,
    title: "Social Media Marketing 101",
    instructor: "marketing pro",
    rating: 4.6,
    reviewCount: 200,
    level: "Beginner",
    lessons: 15,
    duration: "2 hours 10 mins",
    comments: 150,
    price: 20,
    priceType: "lifetime",
    category: "social-media",
    thumbnail: "/images/course/course3.jpg",
    studentCount: 890,
  },
  {
    id: 10,
    title: "2D Animation Fundamentals",
    instructor: "anim studio",
    rating: 4.9,
    reviewCount: 75,
    level: "Beginner",
    lessons: 22,
    duration: "5 hours",
    comments: 60,
    price: 40,
    priceType: "lifetime",
    category: "animation",
    thumbnail: "/images/course/course4.jpg",
    studentCount: 310,
  },
  {
    id: 11,
    title: "Creative Marketing Strategies",
    instructor: "brand experts",
    rating: 4.4,
    reviewCount: 110,
    level: "Intermediate",
    lessons: 18,
    duration: "3 hours 20 mins",
    comments: 90,
    price: 28,
    priceType: "lifetime",
    category: "creative-marketing",
    thumbnail: "/images/course/course5.jpg",
    studentCount: 520,
  },
  {
    id: 12,
    title: "Film & Video Editing Pro",
    instructor: "cinema lab",
    rating: 4.7,
    reviewCount: 88,
    level: "Advanced",
    lessons: 30,
    duration: "6 hours 15 mins",
    comments: 70,
    price: 45,
    priceType: "lifetime",
    category: "film-video",
    thumbnail: "/images/course/course6.jpg",
    studentCount: 440,
  },
  {
    id: 13,
    title: "Handmade Crafts Workshop",
    instructor: "craft house",
    rating: 4.5,
    reviewCount: 65,
    level: "Beginner",
    lessons: 12,
    duration: "2 hours",
    comments: 48,
    price: 18,
    priceType: "lifetime",
    category: "crafts",
    thumbnail: "/images/course/course1.jpg",
    studentCount: 290,
  },
  {
    id: 14,
    title: "Photography Essentials",
    instructor: "photo master",
    rating: 4.8,
    reviewCount: 140,
    level: "Beginner",
    lessons: 16,
    duration: "3 hours",
    comments: 110,
    price: 25,
    priceType: "lifetime",
    category: "photography",
    thumbnail: "/images/course/course2.jpg",
    studentCount: 720,
  },
  {
    id: 15,
    title: "Full Stack Web Development",
    instructor: "code academy",
    rating: 4.9,
    reviewCount: 300,
    level: "Intermediate",
    lessons: 40,
    duration: "10 hours",
    comments: 250,
    price: 50,
    priceType: "lifetime",
    category: "web-development",
    thumbnail: "/images/course/course3.jpg",
    studentCount: 1200,
  },
  {
    id: 16,
    title: "Gourmet Cooking at Home",
    instructor: "chef studio",
    rating: 4.6,
    reviewCount: 90,
    level: "Beginner",
    lessons: 14,
    duration: "2 hours 30 mins",
    comments: 75,
    price: 22,
    priceType: "lifetime",
    category: "cooking",
    thumbnail: "/images/course/course4.jpg",
    studentCount: 480,
  },
  {
    id: 17,
    title: "Digital Illustration Masterclass",
    instructor: "art studio",
    rating: 4.7,
    reviewCount: 105,
    level: "Intermediate",
    lessons: 25,
    duration: "4 hours 45 mins",
    comments: 88,
    price: 35,
    priceType: "lifetime",
    category: "digital-illustration",
    thumbnail: "/images/course/course5.jpg",
    studentCount: 560,
  },
  {
    id: 18,
    title: "Marketing Analytics Deep Dive",
    instructor: "data pro",
    rating: 4.5,
    reviewCount: 78,
    level: "Advanced",
    lessons: 20,
    duration: "3 hours 50 mins",
    comments: 62,
    price: 38,
    priceType: "lifetime",
    category: "marketing",
    thumbnail: "/images/course/course6.jpg",
    studentCount: 340,
  },
];
